version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/user-db
    depends_on:
      - mongo

  todo-service:
    build:
      context: ./todo-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo-db
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  notification-service:
    build:
      context: ./notification-service
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

