/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LoginForm {
    }
    interface LoginRedirect {
    }
    interface TodoList {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLoginFormElement extends Components.LoginForm, HTMLStencilElement {
    }
    var HTMLLoginFormElement: {
        prototype: HTMLLoginFormElement;
        new (): HTMLLoginFormElement;
    };
    interface HTMLLoginRedirectElement extends Components.LoginRedirect, HTMLStencilElement {
    }
    var HTMLLoginRedirectElement: {
        prototype: HTMLLoginRedirectElement;
        new (): HTMLLoginRedirectElement;
    };
    interface HTMLTodoListElement extends Components.TodoList, HTMLStencilElement {
    }
    var HTMLTodoListElement: {
        prototype: HTMLTodoListElement;
        new (): HTMLTodoListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "login-form": HTMLLoginFormElement;
        "login-redirect": HTMLLoginRedirectElement;
        "todo-list": HTMLTodoListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LoginForm {
    }
    interface LoginRedirect {
    }
    interface TodoList {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "login-form": LoginForm;
        "login-redirect": LoginRedirect;
        "todo-list": TodoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "login-form": LocalJSX.LoginForm & JSXBase.HTMLAttributes<HTMLLoginFormElement>;
            "login-redirect": LocalJSX.LoginRedirect & JSXBase.HTMLAttributes<HTMLLoginRedirectElement>;
            "todo-list": LocalJSX.TodoList & JSXBase.HTMLAttributes<HTMLTodoListElement>;
        }
    }
}
